services:
  postgres:
    image: postgres:15
    container_name: paykit_postgres
    environment:
      POSTGRES_USER: paykit
      POSTGRES_PASSWORD: paykit_secret
      POSTGRES_DB: paykit
    ports:
      - "5434:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./internal/storage/migrate.sql:/docker-entrypoint-initdb.d/migrate.sql

volumes:
  postgres_data: