package api

import (
	"net/http"
	"os"
	"time"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/Brown-Moses/paykit/docs" // generated by swag init
	"github.com/Brown-Moses/paykit/internal/auth"
	"github.com/Brown-Moses/paykit/internal/metrics"
	"github.com/Brown-Moses/paykit/internal/storage"
	webhooks "github.com/Brown-Moses/paykit/internal/webhook"

	"github.com/gin-gonic/gin"
)

func NewRouter(verifier *auth.Verifier, store *storage.Store, startTime time.Time) *gin.Engine {
	r := gin.Default()
	r.SetTrustedProxies(nil)

	webHook := webhooks.NewHandler(verifier, store, startTime)

	// Admin Password Auth setup
	adminPassword := os.Getenv("ADMIN_PASSWORD")
	if adminPassword == "" {
		adminPassword = "admin" // secure default/fallback
	}

	// DB Status check middleware for UI page requests
	r.Use(func(c *gin.Context) {
		path := c.Request.URL.Path
		// Only check database health for main portal pages and operator dashboard UI requests
		isUI := path == "/" || 
			(len(path) >= 7 && path[:7] == "/portal") || 
			(len(path) >= 9 && path[:9] == "/operator")

		if isUI {
			if err := store.Ping(); err != nil {
				c.Header("Cache-Control", "no-cache, no-store, must-revalidate")
				c.Status(http.StatusServiceUnavailable)
				c.File("./web/503.html")
				c.Abort()
				return
			}
		}
		c.Next()
	})

	// Static UI assets routing
	r.StaticFile("/", "./web/landing.html")
	r.Static("/portal", "./web/merchant")

	operatorPortal := r.Group("/operator", gin.BasicAuth(gin.Accounts{
		"admin": adminPassword,
	}))
	operatorPortal.Static("", "./web/admin")

	// Global 404 Page Router
	r.NoRoute(func(c *gin.Context) {
		c.Status(http.StatusNotFound)
		c.File("./web/404.html")
	})

	// System
	r.GET("/health", webHook.Health)

	// Prometheus (scrape endpoint) — no merchant auth
	r.GET("/metrics/prometheus", func(c *gin.Context) {
		metrics.PrometheusHandler().ServeHTTP(c.Writer, c.Request)
	})

	//swagger docs ui
	r.GET("/docs/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Public
	r.POST("/merchants", webHook.CreateMerchant)
	r.POST("/auth/login", webHook.Login)

	// Webhook — IP whitelisted, no API key needed, quota enforced
	r.POST("/webhook/momo/:merchant_id",
		auth.IPWhitelist(),
		auth.TierEnforcement(store),
		webHook.HandleMoMoWebhook,
	)

	// Protected — all plural, all consistent
	protected := r.Group("/")
	protected.Use(auth.RequireAPIKey(store))
	{
		protected.GET("/transactions", webHook.ListTransactions)
		protected.GET("/transactions/:id", webHook.GetTransaction)
		protected.GET("/transactions/:id/deliveries", webHook.GetDeliveryLogs)
		protected.GET("/metrics", webHook.Metrics)
		protected.PUT("/merchants/webhook-url", webHook.UpdateWebhookURL)

		// DLQ — merchant specific
		protected.GET("/dlq", webHook.ListDLQ)
		protected.POST("/dlq/:id/retry", webHook.RetryDLQ)
	}

	// Operator Admin API endpoints
	adminAPI := r.Group("/admin/api", gin.BasicAuth(gin.Accounts{
		"admin": adminPassword,
	}))
	{
		adminAPI.GET("/merchants", webHook.AdminListMerchants)
		adminAPI.PUT("/merchants/:id/toggle", webHook.AdminToggleMerchant)
		adminAPI.PUT("/merchants/:id/quota", webHook.AdminUpdateMerchantQuota)
	}

	return r
}
