package api

import (
	"time"

	swaggerFiles "github.com/swaggo/files"
	ginSwagger "github.com/swaggo/gin-swagger"

	_ "github.com/Brown-Moses/paykit/docs" // generated by swag init
	"github.com/Brown-Moses/paykit/internal/auth"
	"github.com/Brown-Moses/paykit/internal/storage"
	webhooks "github.com/Brown-Moses/paykit/internal/webhook"
	"github.com/gin-gonic/gin"
)

func NewRouter(verifier *auth.Verifier, store *storage.Store, startTime time.Time) *gin.Engine {
	r := gin.Default()
	r.SetTrustedProxies(nil)

	webHook := webhooks.NewHandler(verifier, store, startTime)

	// System
	r.GET("/health", webHook.Health)

	//swagger docs ui
	r.GET("/docs/*any", ginSwagger.WrapHandler(swaggerFiles.Handler))

	// Public
	r.POST("/webhook/momo/:merchant_id", webHook.HandleMoMoWebhook)
	r.POST("/merchants", webHook.CreateMerchant)

	// Protected — all plural, all consistent
	protected := r.Group("/")
	protected.Use(auth.RequireAPIKey(store))
	{
		protected.GET("/transactions", webHook.ListTransactions)
		protected.GET("/transactions/:id", webHook.GetTransaction)
		protected.GET("/transactions/:id/deliveries", webHook.GetDeliveryLogs)
	}
	return r
}
